### ISSUE TITLE
Last.fm data doesn't get fetched

### ISSUE THREAD

**Issue by rollecode** [hakko/subsonic#41]
I recently reinstalled Subsonic to another server and noticed Artists dropdown is empty and tag configuration displays "Sorry, but you don't have enough music for this to be meaningful. Please add some more artists." even if everything has been scanned.

Last.fm redesigned their site and API so I think it's related to this.

```
[2015-09-07 12:54:29] DEBUG UserRecommendedArtistsService - allowed: false, successful: false, errorCode: 0, errorMessage: null, errorRecoverable: false, responseBody: null
[2015-09-07 12:54:29] ERROR SearchIndexUpdateExecutorService - com.github.hakko.musiccabinet.service.lastfm.ArtistTopTagsService@617da81b failed with an unexpected error.
java.lang.NullPointerException
    at com.github.hakko.musiccabinet.parser.lastfm.ArtistTopTagsHandler.endElement(ArtistTopTagsHandler.java:62)
    at com.ctc.wstx.sr.BasicStreamReader.fireSaxEndElement(BasicStreamReader.java:1698)
    at com.ctc.wstx.sax.WstxSAXParser.fireEvents(WstxSAXParser.java:614)
    at com.ctc.wstx.sax.WstxSAXParser.parse(WstxSAXParser.java:537)
    at com.ctc.wstx.sax.WstxSAXParser.parse(WstxSAXParser.java:307)
    at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
    at com.github.hakko.musiccabinet.parser.AbstractSAXParserImpl.parseFromStream(AbstractSAXParserImpl.java:29)
    at com.github.hakko.musiccabinet.parser.lastfm.ArtistTopTagsParserImpl.loadTopTags(ArtistTopTagsParserImpl.java:23)
    at com.github.hakko.musiccabinet.parser.lastfm.ArtistTopTagsParserImpl.<init>(ArtistTopTagsParserImpl.java:18)
    at com.github.hakko.musiccabinet.service.lastfm.ArtistTopTagsService.updateSearchIndex(ArtistTopTagsService.java:47)
    at com.github.hakko.musiccabinet.service.lastfm.SearchIndexUpdateExecutorService$Worker.run(SearchIndexUpdateExecutorService.java:78)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by rollecode** [comment]
Perhaps related: https://getsatisfaction.com/lastfm/topics/api-known-issues

```
We are aware of the following problems with the Last.fm APIs:

artists.getinfo returns incorrect listeners/playcounts for uncorrected artists

artist.search returns errors

artist.gettopalbums returns errors

If your problem isn’t included on that list please let us know and we will start tracking it.
```

**Comment by noone5** [comment]
I have the same problem
